image: rust:latest

stages:
  - test
  - pages

test:
  stage: test
  script:
    - cargo test

doc:
  stage: test
  script:
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc

pages:
  stage: pages
  needs:
    - doc
  script:
    - cp -r target/doc public
  artifacts:
    paths:
      - public
  only:
    - master

ap201:
  stage: test
  script:
    - cargo run --bin esprc -- ./schemas/APs/10303-201-aim-long.exp
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
