stages:
  - test
  - pages

test:
  image: rust:latest
  stage: test
  script:
    - cargo test
  allow_failure: true

pages:
  image: rust:latest
  stage: pages
  script:
    - cargo doc --no-deps
    - cp -r target/doc public
  artifacts:
    paths:
      - public
  only:
    - master
