image: rust:latest

stages:
  - test
  - pages

test:
  stage: test
  script:
    - cargo test
  cache:
    key: cargo
    paths:
      - target/
      - cargo/
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo

pages:
  stage: pages
  script:
    - cargo doc --no-deps
    - cp -r target/doc public
  artifacts:
    paths:
      - public
  only:
    - master
