image: rust:latest

stages:
  - test
  - pages

test:
  stage: test
  script:
    - cargo test

test-ignored:
  stage: test
  script:
    - cargo test -- --ignored
  allow_failure: true

pages:
  stage: pages
  script:
    - cargo doc --no-deps
    - cp -r target/doc public
  artifacts:
    paths:
      - public
  only:
    - master
