image: rust:latest

cache:
  key: cargo
  paths:
    - target/
    - cargo/
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

stages:
  - test
  - pages

test:
  stage: test
  script:
    - cargo test

pages:
  stage: pages
  script:
    - cargo doc --no-deps
    - cp -r target/doc public
  artifacts:
    paths:
      - public
  only:
    - master
