[package]
name = "espr"
version = "0.1.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>", "Toshiki Teramura <teramura@ricos.co.jp"]
edition = "2018"

[dependencies]
Inflector = "0.11.4"
regex = "1.4.2"
lazy_static = "1.4.0"
trybuild = "1.0.35"
nom = "6.0.0"
derive_more = "0.99.11"
syn = "1.0.48"
quote = "1.0.7"
proc-macro2 = "1.0.24"
thiserror = "1.0.22"
maplit = "1.0.2"
itertools = "0.9.0"

[dev-dependencies]
espr-runtime = { version = "0.1.0", path = "../espr-runtime" }
