[package]
name = "espr"
version = "0.1.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>", "Toshiki Teramura <teramura@ricos.co.jp"]
edition = "2018"

[dependencies]
# For parser
nom = "6.0.1"

# For Rust code generation
syn = "1.0.56"
quote = "1.0.8"
proc-macro2 = "1.0.24"

# Utilities
Inflector = "0.11.4"
derive_more = "0.99.11"
itertools = "0.10.0"
maplit = "1.0.2"
thiserror = "1.0.23"

[dev-dependencies]
espr-runtime = { version = "0.1.0", path = "../espr-runtime" }
trybuild = "1.0.38"
