[package]
name = "ruststep-derive"
version = "0.1.0"
edition = "2018"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0.9"
proc-macro2 = "1.0.27"
syn = { version = "1.0.72", features = ["full", "extra-traits"] }
