[package]
name = "ruststep"
version = "0.1.0"
authors = ["Toshiki Teramura <teramura@ricos.co.jp>", "Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"

[features]
default = []
ap201 = []

[dependencies]
derive-new = "0.5.9"
derive_more = "0.99.16"
dyn-clone = "1.0.4"
nom = "7.0.0"
serde = { version = "1.0.129", features = ["derive"] }
thiserror = "1.0.26"
Inflector = "0.11.4"
itertools = "0.10.1"

[dependencies.ruststep-derive]
path = "../ruststep-derive"

[dev-dependencies]
anyhow = "1.0.43"

[package.metadata.release]
no-dev-version = true
