[package]
name = "ruststep"
version = "0.1.0"
authors = ["Toshiki Teramura <teramura@ricos.co.jp>", "Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5.9"
derive_more = "0.99.13"
dyn-clone = "1.0.4"
nom = "6.1.0"
serde = { version = "1.0.124", features = ["derive"]}
thiserror = "1.0.24"
Inflector = "0.11.4"

[dependencies.ruststep-derive]
path = "../ruststep-derive"

[dev-dependencies]
anyhow = "1.0"
