[package]
name = "espr-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.9"
proc-macro2 = "1.0.28"
syn = { version = "1.0.75", features = ["full", "extra-traits"] }
proc-macro-error = "1.0.4"

[dependencies.espr]
path = "../espr"
