name: esprc

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  parse:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ap:
          - "201"
          - "203"
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: "1.56.0"
        profile: minimal
        default: true
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: run
        args: --bin esprc -- ./schemas/APs/10303-${{ matrix.ap }}-aim-long.exp --check

  generate-ap201:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: "1.56.0"
        profile: minimal
        components: rustfmt
        default: true
        override: true
    - name: Generate AP201 binding
      run: |
        set -eo pipefail
        cargo run --bin esprc -- ./schemas/APs/10303-201-aim-long.exp | rustfmt > ./ruststep/src/ap201.rs
        git diff --exit-code
