name: example

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  ap000_read:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: run
        args: --example ap000_read
